one-acre-fund/oaf-public-charts

.pre-commit-config.yaml, .yamllint.yaml, README.md, artifacthub-repo.yml
=> Add repo id for verified publisher

.gitignore, charts/apicurio/.helmignore, charts/apicurio/Chart.lock, charts/apicurio/Chart.yaml, charts/apicurio/README.md, charts/apicurio/README.md.gotmpl, charts/apicurio/ci/ci-values.yaml, charts/apicurio/templates/NOTES.txt, charts/apicurio/templates/_helpers.tpl, charts/apicurio/templates/apicurio-studio-api-deployment.yaml, charts/apicurio/templates/apicurio-studio-ingresses.yaml, charts/apicurio/templates/apicurio-studio-secrets.yaml, charts/apicurio/templates/apicurio-studio-services.yaml, charts/apicurio/templates/apicurio-studio-ui-deployment.yaml, charts/apicurio/templates/apicurio-studio-ws-deployment.yaml, charts/apicurio/templates/tests/test-connections.yaml, charts/apicurio/values.yaml
=> Apicurio chart

charts/apicurio/Chart.yaml, charts/apicurio/README.md, charts/apicurio/README.md.gotmpl, charts/apicurio/templates/apicurio-studio-api-deployment.yaml, charts/apicurio/templates/apicurio-studio-ui-deployment.yaml, charts/apicurio/templates/apicurio-studio-ws-deployment.yaml, charts/apicurio/values.yaml
=> apicurio-tuning

charts/flagsmith/Chart.yaml, charts/flagsmith/README.md, charts/flagsmith/templates/api-deploy.yaml, charts/flagsmith/templates/frontend-deploy.yaml
=> Fix flagmith resources

charts/fineract/Chart.yaml, charts/fineract/README.md, charts/fineract/ci/ci-values.yaml, charts/fineract/templates/fineract-ingress.yaml, charts/fineract/templates/fineract-mifosx-deployment.yml, charts/fineract/templates/fineract-mifosx-svc.yml, charts/fineract/templates/tests/test-fineract.yaml, charts/fineract/values.yaml
=> Added support for MIFOS-X UI

charts/fineract/Chart.yaml, charts/fineract/README.md, charts/fineract/templates/persistentVolume/fineract-job-pvc.yaml, charts/fineract/templates/persistentVolume/fineract-report-pvc.yaml, charts/fineract/templates/persistentVolume/fineract-rest-pvc.yaml
=> changed access Modes

charts/fineract/Chart.yaml, charts/fineract/README.md, charts/fineract/templates/persistentVolume/fineract-job-pvc.yaml, charts/fineract/templates/persistentVolume/fineract-report-pvc.yaml, charts/fineract/templates/persistentVolume/fineract-rest-pvc.yaml
=> reverted to readwritemany

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/values.yaml
=> bumped up kpi version

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/deployment-master.yaml, charts/n8n/templates/deployment-worker.yaml
=> fix argument

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/deployment-worker.yaml
=> overide startup command for workers

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/deployment-worker.yaml
=> disable probes on workers

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/_helpers.tpl, charts/n8n/templates/deployment-proxy.yaml, charts/n8n/templates/deployment-worker.yaml, charts/n8n/templates/secret.yaml, charts/n8n/values.yaml
=> add auth proxy

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/secret.yaml
=> fix secret condition

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/deployment-proxy.yaml, charts/n8n/templates/secret.yaml, charts/n8n/values.yaml
=> change env vars

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/deployment-proxy.yaml
=> remove resources

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/deployment-proxy.yaml, charts/n8n/values.yaml
=> remove variable

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/values.yaml
=> quote booleans

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/deployment-proxy.yaml
=> quote strings

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/deployment-proxy.yaml, charts/n8n/templates/secret.yaml
=> fix secret value

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/deployment-proxy.yaml
=> fix variable name

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/deployment-proxy.yaml, charts/n8n/templates/service-proxy.yaml
=> fix variable

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/secret.yaml
=> remove unused secrets

charts/nocodb/Chart.yaml, charts/nocodb/README.md
=> bump version

charts/nocodb/Chart.yaml, charts/nocodb/README.md, charts/nocodb/templates/deployment.yaml
=> fix template syntax

charts/nocodb/Chart.yaml, charts/nocodb/README.md, charts/nocodb/values.yaml
=> disable sa creation

charts/apicurio/Chart.yaml, charts/apicurio/README.md, charts/apicurio/templates/apicurio-studio-ingresses.yaml
=> add ingress annotation

charts/geonode/README.md, charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml, charts/kobotoolbox/values.yaml
=> add switch

charts/kobotoolbox/templates/kobo-deploy.yaml
=> fix syntax

.github/workflows/helm-release.yaml, charts/growthbook/Chart.yaml, charts/growthbook/README.md, charts/growthbook/templates/deployment.yaml, charts/growthbook/templates/pvc.yaml, charts/growthbook/values.yaml
This PR updates GrowthBook helm chart to fix helm release.
=> Growthbook chart update

charts/growthbook/Chart.yaml, charts/growthbook/templates/deployment.yaml
=> change mount name

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/_helpers.tpl
=> fix postgres references

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/_helpers.tpl
=> fix url references

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/_helpers.tpl, charts/kobotoolbox/templates/kobo-deploy.yaml, charts/kobotoolbox/templates/kobo-secrets.yaml, charts/kobotoolbox/values.yaml
=> use azure blob storage

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml
=> volume mounts still being referenced

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/_helpers.tpl, charts/kobotoolbox/values.yaml
=> add kobocat azure storage

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/_helpers.tpl, charts/kobotoolbox/values.yaml
=> fix spacing

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/templates/kobo-deploy.yaml
=> restore original commands

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-conf.yaml
=> add lazy-apps to kobocat as well

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/metrics-exporter.yaml
=> add uwsgi metrics exporter

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/metrics-exporter.yaml
=> fix exporter arguments

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml, charts/kobotoolbox/values.yaml
=> add exporter kill switch

charts/apicurio/Chart.yaml, charts/apicurio/README.md, charts/flagsmith/Chart.lock, charts/flagsmith/Chart.yaml, charts/flagsmith/README.md
=> upgrade flagsmith keycloak

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml
=> re-add init container command

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml
=> remove quotes

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml
=> try downgrading dependency

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml
=> chain commands

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml
=> fix chaining

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml
=> change uwsgi ini  mount pathe

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml
=> use tcp for metrics

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/metrics-exporter.yaml
=> fix listening port

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/_helpers.tpl
=> increase default respawn thresholds

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/templates/kobo-conf.yaml
=> increase default rss respawn memory threshold

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/_helpers.tpl, charts/kobotoolbox/templates/kobo-conf.yaml
=> increase default min worker lifespan

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/_helpers.tpl
=> increase workers

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/_helpers.tpl, charts/kobotoolbox/templates/kobo-conf.yaml
=> disbale cheaper algorithm

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/_helpers.tpl, charts/kobotoolbox/templates/kobo-conf.yaml
=> increase worker lifetime

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-conf.yaml
=> disable respawning

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml, charts/kobotoolbox/values.yaml
=> allow disabling of media local storage

charts/growthbook/Chart.yaml, charts/growthbook/templates/deployment.yaml, charts/growthbook/templates/secrets.yaml
This PR defines smtp password as secret and fixes typo in license secret name
=> Fix Growthbook license and smtp password secrets

charts/kutt/.helmignore, charts/kutt/Chart.yaml, charts/kutt/templates/NOTES.txt, charts/kutt/templates/_helpers.tpl, charts/kutt/templates/deployment.yaml, charts/kutt/templates/hpa.yaml, charts/kutt/templates/ingress.yaml, charts/kutt/templates/service.yaml, charts/kutt/templates/serviceaccount.yaml, charts/kutt/templates/tests/test-connection.yaml, charts/kutt/values.yaml
=> add kutt helm chart

charts/kutt/Chart.yaml, charts/kutt/README.md, charts/kutt/templates/deployment.yaml, charts/kutt/templates/secret.yaml
=> add secrets

charts/kutt/Chart.yaml, charts/kutt/README.md, charts/kutt/templates/deployment.yaml
=> change container port

charts/kutt/Chart.yaml, charts/kutt/README.md, charts/kutt/templates/deployment.yaml, charts/kutt/templates/service.yaml
=> remove main port

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-deploy.yaml
=> add media dir irespective of storage location

charts/kutt/Chart.yaml, charts/kutt/README.md, charts/kutt/templates/secret.yaml, charts/kutt/values.yaml
=> disable secret quoting

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-flower.yaml, charts/kobotoolbox/values.yaml
=> add optional flower monitoring of tasks

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-flower.yaml
=> hide secret

charts/kobotoolbox/Chart.yaml, charts/kobotoolbox/README.md, charts/kobotoolbox/templates/kobo-flower.yaml
=> fix redis port

charts/mautic/Chart.yaml, charts/mautic/README.md, charts/mautic/README.md.gotmpl, charts/mautic/requirements.lock, charts/mautic/templates/NOTES.txt, charts/mautic/templates/_helpers.tpl, charts/mautic/templates/deployment.yaml, charts/mautic/templates/ingress.yaml, charts/mautic/templates/pvc.yaml, charts/mautic/templates/secret.yaml, charts/mautic/templates/service.yaml, charts/mautic/test-values.yaml, charts/mautic/values.yaml
=> Add mautic

charts/sydent/Chart.yaml, charts/sydent/README.md
=> add matrix severname variable

charts/sydent/Chart.yaml, charts/sydent/README.md, charts/sydent/templates/deployment.yaml, charts/sydent/values.yaml
=> add template path

charts/pgbouncer/Chart.yaml, charts/pgbouncer/templates/deployment.yaml
Addresses a syntax problem in the deployment.yaml file by rectifying the indentation, ensuring the YAML code is correctly formatted. This resolves the issue where improper syntax was leading to deployment failures.
N/A *(If there are no additional details to add)*
=> Fix deployment.yaml syntax issue

charts/pgbouncer/Chart.yaml, charts/pgbouncer/README.md, charts/pgbouncer/templates/deployment.yaml, charts/pgbouncer/values.yaml
In this pull request, I've made several significant updates to the server TLS configurations and related settings:
1. **Separate Value for Pgbouncer Database:**
- Introduced a distinct value for the Pgbouncer database, allowing clear and independent management of its configurations. This enhances the maintainability and readability of the codebase.
2. **Updated TLS Values Section:**
- Modified the TLS values section to ensure accurate and secure server configurations. This includes necessary updates to certificates, keys, and related configurations, enhancing the overall security of the server.
```yaml
tls:
enabled: true
certificatesSecret: oaf-tls
certFilename: tls.crt
certKeyFilename: tls.key
```
These changes ensure that TLS is enabled with the specified certificate and key filenames. …
=> Fix server tls configurations, update tls values section, and add a separate value for pgbouncer database

README.md, charts/pgbouncer/Chart.yaml, charts/pgbouncer/README.md, charts/pgbouncer/README.md.gotmpl, charts/pgbouncer/templates/_helpers.tpl, charts/pgbouncer/templates/configmap.yaml, charts/pgbouncer/templates/deployment.yaml, charts/pgbouncer/templates/secret.yaml, charts/pgbouncer/templates/service.yaml, charts/pgbouncer/templates/serviceaccount.yaml, charts/pgbouncer/values.yaml
I have made significant changes to the Helm chart to enhance its configurability by introducing the ability to source environment variables from either ConfigMaps or Secrets. This modification provides greater flexibility and security in managing environment variables within our application.
In this pull request, the key changes include:
- Allowing the Helm chart to source environment variables from both ConfigMaps and Secrets.
- Enhancing the chart to dynamically fetch environment variables from the specified ConfigMap or Secret, providing a more robust and versatile configuration mechanism.
By implementing these changes, we are improving the Helm chart's compatibility with various deployment scenarios, making it more adaptable to specific user requirements.
To ensure the quality and …
=> Use configmap and secrets for env

charts/apicurio/Chart.yaml, charts/apicurio/README.md, charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/deployment-master.yaml, charts/n8n/templates/deployment-worker.yaml, charts/n8n/values.yaml, charts/pgbouncer/Chart.yaml, charts/pgbouncer/README.md
this is beacuse different images have differing mount points
=> make the volume mont paths configurable

.github/workflows/helm-release.yaml
upgrade workflow chart releser
=> upgrade chart releaser

.github/workflows/helm-release.yaml, charts/mautic/Chart.lock, charts/mautic/Chart.yaml, charts/mautic/README.md, charts/mautic/templates/ingress.yaml
=> fix mautic ingress

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/tests/test-connection.yaml
=> chore: bump n8n chart version to 0.1.50

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/n8n/templates/tests/test-connection.yaml
=> chore: bump n8n chart version to 0.1.51

charts/uptime-wrapper/Chart.yaml, charts/uptime-wrapper/README.md, charts/uptime-wrapper/values.yaml
=> chore: Update uptime-wrapper chart to use new image repository

charts/n8n/Chart.yaml, charts/n8n/README.md, charts/uptime-wrapper/Chart.yaml, charts/uptime-wrapper/README.md, charts/uptime-wrapper/values.yaml
=> chore: Update image repository for uptime-wrapper chart

charts/mautic/Chart.yaml, charts/mautic/templates/ingress.yaml
The current deployment with Helm chart is failing with the following error:
```
W0604 11:47:03.579267   62711 warnings.go:70] unknown field "spec.rules[0].http.paths[0].backend.serviceName"
W0604 11:47:03.579317   62711 warnings.go:70] unknown field "spec.rules[0].http.paths[0].backend.servicePort"
Error: INSTALLATION FAILED: 1 error occurred:
* Ingress.networking.k8s.io "mautic" is invalid: [spec.rules[0].http.paths[0].pathType: Unsupported value: "prefix": supported values: "Exact", "ImplementationSpecific", "Prefix", spec.rules[0].http.paths[0].backend: Invalid value: "": resource or service backend is required]
```
The error messages are related to your Kubernetes Ingress configuration. Here are the issues that need to be addressed:
```
W0604 11:47:03.579267   62711 warnings.go:70] …
```
=> fix(Mautic Ingress): Resolved Invalid PathType and Service Backend

README.md
This pull request includes updates to the `README.md` file to add new resources to the list of tools.
Additions to the list of tools:
* Added `Nocodb` to the list of tools. (`README.md`)
* Added `Sydent` to the list of tools. (`README.md`)
* Added `Uptime Wrapper` to the list of tools. (`README.md`)
=> Add Nocodb, Sydent, and Uptime Wrapper to the list of supported applications

charts/nocodb/Chart.yaml, charts/nocodb/README.md, charts/nocodb/templates/deployment.yaml, charts/nocodb/values.yaml
This pull request includes several changes to the NocoDB Helm chart, focusing on modifying database-related configurations, and improving template inclusions.
* Updated the chart version from `0.3.3` to `0.3.4` in `charts/nocodb/Chart.yaml` and `charts/nocodb/README.md`.
* Replaced `template` function calls with `include` function calls for better readability and consistency in `charts/nocodb/templates/deployment.yaml`.
=> fix(helm): quote databasePort to fix unmarshal error
